### ISSUE TITLE
Ubuntu 18.04 Automake 

### ISSUE THREAD

**Issue by tokenwizard** [jlledom/doclone#2]
I'm running latest Ubuntu LTS with automake 1.16.1 and I cannot compile doclone using the download link provided on the website. 

First, I have to install many "-dev" packages (libparted-dev, etc..) to get through the configure steps. Now when trying to make it, I get an error that automake 1.14 is not installed. 

Does doclone require that specific version of automake or should it be able to use >=1.14?

**Comment by tokenwizard** [comment]
Also, 
you state:
### 1.5 Compliling doclone
As usual, to compile doclone you only need to execute the classic commands:
	./configure
	make
   
but on my attempt to try a fresh install via git, after installing the necessary dependencies ./configure does not work. The script does not exist on a fresh git clone. 

Maybe the installation instructions need to be updated?
![doclone-error](https://user-images.githubusercontent.com/24832561/53598260-37ccf400-3b72-11e9-885f-a2d413620171.png)

**Comment by jlledom** [comment]
About the -dev packages, you're right. The code has some dependencies as you may see in configure.ac. You'll need automake and other autotools.

About your other question, in the website you'll see you'll need to run "autoreconf -i" before.
[http://doclone.nongnu.org/#libdocs](http://doclone.nongnu.org/#libdocs)

**Comment by tokenwizard** [comment]
Yeah,
I saw that and gave it a try....

I'm guessing this is related to my other question about automake 1.14 requirements? Can it not compile with newer automake (ie. 1.16)?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jlledom** [comment]
I'd say it should work with automake 1.16, have you tried?

Missatge de tokenwizard <notifications@github.com> del dia dv., 1 de març
2019 a les 16:06:
